### ISSUE TITLE
error while installing older version of pefile

### ISSUE THREAD

**Issue by limited-root** [erocarrera/pefile#118]
i had some problems with new pefile in cuckoo analysis, so developer suggested me to use older version of pefile (2013). 
 but i couldnt install it by sudo python setup.py, can u help me. this is the error:
`python setup.py install Traceback (most recent call last): File "setup.py", line 8, in <module> import pefile File "/home/administrator/Desktop/thesis final/pefile-pefile-1.2.10-139/pefile.py", line 25, in <module> __version__ = '1.2.10-%d' % int( __revision__[21:-2] ) ValueError: invalid literal for int() with base 10: ''`

i even tried: [https://github.com/erocarrera/pefile/pull/72/files](url)

but then i get:
`sudo python setup.py
  File "setup.py", line 1
    +#!/usr/bin/python
                     ^
SyntaxError: invalid syntax`

**Comment by limited-root** [comment]
i found the solution, by using 
`https://github.com/erocarrera/pefile/blob/4f685a2f8b732db4803a47ba42ece688f1e72a89/pefile.py`
and
`https://github.com/erocarrera/pefile/blob/4f685a2f8b732db4803a47ba42ece688f1e72a89/setup.py`
