### ISSUE TITLE
Call to non-existent function `convert_to_printable`

### ISSUE THREAD

**Issue by chapinb** [erocarrera/pefile#187]
When running the below code I receive the following error/traceback:

```python
>>> from pefile import PE
>>> pe = PE("elasticsearch-5.4.0/bin/elasticsearch-service-mgr.exe")
>>> ped = pe.dump_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.6/site-packages/pefile.py", line 4777, in dump_dict
    resource_id_list.append(convert_to_printable(res_string))
NameError: name 'convert_to_printable' is not defined
```

Additional version information:

```python
>>> pefile.__version__
'2016.3.28'
>>> sys.version
'3.6.1 (default, Mar 23 2017, 21:50:17) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]'
```

Possible duplicate of #178 
Executable used in this test: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.zip

**Comment by bernhl** [comment]
This was fixed in https://github.com/erocarrera/pefile/commit/ef87dda480ab7a412838cc06b9824b31caa22a11#diff-c948f10453930d93b48fd0edbe7fcc2dL4976
