### ISSUE TITLE
UnboundLocalError: local variable 'format' referenced before assignment

### ISSUE THREAD

**Issue by CrimsonGlory** [erocarrera/pefile#194]
```
>>> import pefile
>>> file = open('c0cdcbba5572afac6b80735331d9e71556542b71.codex','r').read()
>>> library = pefile.PE(data=file, fast_load=True)
>>> dir_folders = [
...                     pefile.DIRECTORY_ENTRY.get('IMAGE_DIRECTORY_ENTRY_IMPORT'),
...                     pefile.DIRECTORY_ENTRY.get('IMAGE_DIRECTORY_ENTRY_EXPORT'),
...                     pefile.DIRECTORY_ENTRY.get('IMAGE_DIRECTORY_ENTRY_TLS'),
...                     pefile.DIRECTORY_ENTRY.get('IMAGE_DIRECTORY_ENTRY_SECURITY'),
...                     pefile.DIRECTORY_ENTRY.get('IMAGE_DIRECTORY_ENTRY_RESOURCE')]
>>>
>>> dir_folders
[1, 0, 9, 4, 2]
>>> library.parse_data_directories(directories=dir_folders)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pefile.py", line 2370, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/usr/local/lib/python2.7/dist-packages/pefile.py", line 2498, in parse_directory_tls
    format,
UnboundLocalError: local variable 'format' referenced before assignment
>>> 

```

Download file: (pass codex)
```
https://www.mediafire.com/?tz6xcu1n7xtrjj0
```

warning: do not execute the file.

**Comment by bernhl** [comment]
Should be fixed since https://github.com/erocarrera/pefile/commit/34a3f19d8eb058ba2040c1edac8f9dcf7e86c14a

**Comment by CrimsonGlory** [comment]
I've just confirmed it is fixed.
