### ISSUE TITLE
peutils: Signatures with version number extraction

### ISSUE THREAD

**Issue by ChaosCom** [erocarrera/pefile#230]
Hello Ero,

I have a userdb.txt file containing signatures for peutils.SignatureDatabase(...) consumption

that look for example like 

```
[File Analyzer Compiled Datafile Version %v3.%v4]
signature = 46 69 6C 65 20 41 6E 61 6C 79 7A 65 72 20 43 6F 6D 70 69 6C 65 64 20 44 61 74 61 66 69 6C 65 20 56 65 72 73 69 6F 6E ?? V3 ?? V4
ep_only = false
```

or
 
```
[PolyCryptor by SMT Version %v3.%v4]
signature = EB ?? 28 50 6F 6C 79 53 63 72 79 70 74 20 V3 ?? V4 20 62 79 20 53 4D 54 29
ep_only = true
```

where the goal was obviously to use some of the bytes in the signature (represented by literals starting with **V**) to identify the version number and use that in the output of the match. 
However, loading such a signature database file results in 

> Traceback (most recent call last):
>   File "packerid.py", line 59, in <module>
>     signatures = peutils.SignatureDatabase('userdb.txt')
>   File "C:\software\python\lib\site-packages\peutils.py", line 76, in __init__
>     self.__load(filename=filename, data=data)
>   File "C:\software\python\lib\site-packages\peutils.py", line 443, in __load
>     signature_bytes = [to_byte(b) for b in signature.split()]
>   File "C:\software\python\lib\site-packages\peutils.py", line 427, in to_byte
>     return int(value, 16)
> ValueError: invalid literal for int() with base 16: 'V3'

So apparently to_byte() doesn't like this kind of input...

My question now is: 
Was there at any point in time support for this kind of "formatted output" in peutils and was support for for that dropped?

**Comment by wesinator** [comment]
#192
