### ISSUE TITLE
Fail to write file if only timestamps are updated.

### ISSUE THREAD

**Issue by s3c** [erocarrera/pefile#271]
When running the following code in Python 3.75:

```
import sys
import pefile

pe = pefile.PE(sys.argv[1])
pe.FILE_HEADER.TimeDateStamp = 0
pe.DIRECTORY_ENTRY_EXPORT.struct.TimeDateStamp = 0
pe.DIRECTORY_ENTRY_RESOURCE.struct.TimeDateStamp = 0
pe.write(filename=sys.argv[1])
```

I get a error associated with writing to a file with an open handle:

> Traceback (most recent call last): File "scripts\update_timestamp.py", line 15, in <module> pe.write(filename=out_filename) File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pefile.py", line 2284, in write f = open(filename, 'wb+') OSError: [Errno 22] Invalid argument: 'test.exe'

However, when adding the following before the write, it works as expected:

`pe.OPTIONAL_HEADER.CheckSum = pe.generate_checksum()`

I'm guessing the file is held open by something unless specific fields are edited?

**Comment by j-t-1** [comment]
This has been a while so you may not need it.

As far as I understand, this is a bug, and it should save without having to run `pe.OPTIONAL_HEADER.CheckSum = pe.generate_checksum()`.

I was unable to replicate this using the most recent previous commit to this issue, also on Windows.

Would you be able to try on the latest pefile here? Or second choice the latest version using pip if that is more convenient for you.

`pe.generate_checksum()` does do some I/O and running it without assigning to `pe.OPTIONAL_HEADER.CheckSum` possibly would also have made it work.
