### ISSUE TITLE
Bug: Invalid format string in PE.parse_export_directory

### ISSUE THREAD

**Issue by pd-fkie** [erocarrera/pefile#309]
When creating a warning in PE.parse_export_directory on [line 3790](https://github.com/erocarrera/pefile/blob/e7a2d9f40bda10c8a94d424b184b287151a53993/pefile.py#L3790) `{:s}` is used on a `bytes` object but that doesn't
work anymore in python >= 3.8.

Affected lines:
```
self.__warnings.append(
                    'Export directory contains more than 10 repeated entries '
                    '({:s}, 0x{:x}). Assuming corrupt.'.format(
                        symbol_name, symbol_address))
```

Exception:
```
Traceback (most recent call last):
  File "/targets/pefile/fuzz_pefile.py", line 12, in test_one_input
    pefile.PE(data=data)
  File "/targets/pefile/uninst/pefile.py", line 1841, in __init__
    self.__parse__(name, data, fast_load)
  File "/targets/pefile/uninst/pefile.py", line 2202, in __parse__
    self.full_load()
  File "/targets/pefile/uninst/pefile.py", line 2316, in full_load
    self.parse_data_directories()
  File "/targets/pefile/uninst/pefile.py", line 2563, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/targets/pefile/uninst/pefile.py", line 3790, in parse_export_directory
    'Export directory contains more than 10 repeated entries '
TypeError: unsupported format string passed to bytes.__format__
```

Crash file: [crash-3989b46e8b1bd2a26bd1de03e5e35482d43ae9bc](https://github.com/pd-fkie/crashes/raw/main/crash-3989b46e8b1bd2a26bd1de03e5e35482d43ae9bc)

**Comment by insolor** [comment]
@erocarrera, as far as I understand, `{:s}` can be replaced just with `{}`. This works both on Python2 and Python3.
