### ISSUE TITLE
Error in parse dynamic relocations

### ISSUE THREAD

**Issue by GanbaruTobi** [erocarrera/pefile#395]
CLFS.SYS 18446735305110650880 454656 \SystemRoot\System32\drivers\CLFS.SYS
Traceback (most recent call last):
  File "/home/gbaru/Tooling/memflow-py/test.py", line 31, in <module>
    pe = pefile.PE(data=bytes(driver))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 2895, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 3328, in __parse__
    self.full_load()
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 3439, in full_load
    self.parse_data_directories()
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 3735, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 4031, in parse_directory_load_config
    dynamic_relocations = self.parse_dynamic_relocations(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbaru/.virtualenvs/memflow/lib/python3.11/site-packages/pefile.py", line 4070, in parse_dynamic_relocations
    self.__warnings.append(
TypeError: list.append() takes exactly one argument (2 given)

**Comment by oleksii-threatray** [comment]
Can confirm - same issue.

**Comment by j-t-1** [comment]
Version 2023.2.7:

https://github.com/erocarrera/pefile/blob/1ab2807c4eec16041e791d7a6acc68cc23fd5266/pefile.py#L4069-L4074

The %-formatting was incomplete, this is how it is now:

https://github.com/erocarrera/pefile/blob/ac56742648ada10fa2c0d99433a322d471ddb4c2/pefile.py#L4113-L4118

It was found in #368 and fixed in 0463745.

The fix was implemented on 2023.3.10, one month after version 2023.2.7, and so did not go into the next version until 2024.8.26.
