### ISSUE TITLE
Error parsing windows file msvbvm60.dll

### ISSUE THREAD

**Issue by keeely** [erocarrera/pefile#87]
Found for windows 8.1 (32-bit version) loading file msvbvm60.dll from system32.

Traceback (most recent call last):
  File "test.py", line 129, in GetExports
    pe =  pefile.PE(fname)
  File "build\bdist.win32\egg\pefile.py", line 1763, in __init__
  File "build\bdist.win32\egg\pefile.py", line 2102, in __parse__
  File "build\bdist.win32\egg\pefile.py", line 2477, in parse_data_directories
  File "build\bdist.win32\egg\pefile.py", line 2822, in parse_debug_directory
NameError: global name '___IMAGE_DEBUG_MISC_format__' is not defined

**Comment by nyx0** [comment]
Should be fix in #81 sorry for my mistake :(

**Comment by keeely** [comment]
Thanks for the prompt fix, but now I found this one:
For: ctl3d32.dll on Windows XP SP3 (32-bit).
Traceback (most recent call last):
  File "./scan.py", line 12, in <module>
    pe = pefile.PE(dll)
  File "build/bdist.linux-i686/egg/pefile.py", line 1756, in __init__
  File "build/bdist.linux-i686/egg/pefile.py", line 2095, in __parse__
  File "build/bdist.linux-i686/egg/pefile.py", line 2470, in parse_data_directories
  File "build/bdist.linux-i686/egg/pefile.py", line 2835, in parse_debug_directory
UnboundLocalError: local variable 'dbg_type' referenced before assignment

**Comment by nyx0** [comment]
If I'm not mistaken it should be fix in ead55ce.

**Comment by keeely** [comment]
So is there a tree somewhere with both fixes?  I can kick that off on my test set (40,000 windows dlls), but I don't have time to do any merges right now.

**Comment by nyx0** [comment]
Yes, just clone this one https://github.com/nyx0/pefile and do your test with this pefile version. 
Hopefully this is a short solution, waiting for merging.

**Comment by keeely** [comment]
That version seems to have a problem with both files.

**Comment by nyx0** [comment]
You still have issues with this version? Because this is the patched one.

**Comment by keeely** [comment]
I removed the installed egg and copied pefile.py from your branch above, just to be sure I was running the right version.
XP-32-SP3/ctl3d32.dll
Traceback (most recent call last):
  File "./scan.py", line 13, in <module>
    pe = pefile.PE(dll)
  File "/home/windlls/pefile.py", line 1756, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/windlls/pefile.py", line 2095, in __parse__
    self.parse_data_directories()
  File "/home/windlls/pefile.py", line 2470, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/home/windlls/pefile.py", line 2835, in parse_debug_directory
    entries=dbg_type))
UnboundLocalError: local variable 'dbg_type' referenced before assignment

**Comment by keeely** [comment]
dbg.Type == 3 not handled.

**Comment by nyx0** [comment]
My bad for now only IMAGE_DEBUG_TYPE_COFF, IMAGE_DEBUG_TYPE_CODEVIEW and IMAGE_DEBUG_TYPE_MISC are handle.
For your case I have to implement the IMAGE_DEBUG_TYPE_FPO Type 3

**Comment by keeely** [comment]
I understand you have not implemented part of the format handling, but in that case why not just raise pefile.PEFormatError or something like that.  Even if you implement Type3, you still need (IMHO) the else clause to handle 5, or higher.  I'd rather have something that handled that, instead of waiting for the full handling! :-).

**Comment by nyx0** [comment]
Agree :( I will take a look ASAP

**Comment by keeely** [comment]
I put in the else clause in my copy, but then later got:
XP-32-SP3/mfc40.dll
Traceback (most recent call last):
  File "./scan.py", line 13, in <module>
    pe = pefile.PE(dll)
  File "/home/windlls/pefile.py", line 1756, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/windlls/pefile.py", line 2095, in __parse__
    self.parse_data_directories()
  File "/home/windlls/pefile.py", line 2470, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/home/windlls/pefile.py", line 2828, in parse_debug_directory
    self.___IMAGE_DEBUG_MISC_format__,
AttributeError: PE instance has no attribute '___IMAGE_DEBUG_MISC_format__'

**Comment by erocarrera** [comment]
All the versions of mfc40.dll I could get my hands on no longer fail to parse. If you still have the issue please reopen and point me to the file and I'll investigate.
