### ISSUE TITLE
upload latest release to PYPI

### ISSUE THREAD

**Issue by matysek** [erocarrera/pefile#92]
When trying command `pip install pefile` it tries to install old version and not the latest `pefile-2016.3.4`

```
» pip install pefile                                                                                              martin@martin-laptop
Collecting pefile
  Using cached pefile-1.2.10-114.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rae_niyf/pefile/setup.py", line 5
        except ImportError, excp:
                          ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rae_niyf/pefile
```

Uploading tarballs directly to pypi should solve this.

**Comment by enkeyz** [comment]
Same error here.

**Comment by erocarrera** [comment]
I've been playing with pypi in the last couple days. I've updated the package records, deleted the project and recreated it, I've also deleted all the old versions of pefile and yet, the search index seems to not reflect the changes.
The project page (https://pypi.python.org/pypi/pefile/) shows all the updated information but pip appears to not notice, as the search in the site, which still shows the old, no longer existing, version.

I've taken a look at the support issues in pypi and there are open issues such as:

https://sourceforge.net/p/pypi/support-requests/607/
https://sourceforge.net/p/pypi/support-requests/605/

that suggest that there is some problem with the main pypi package index. My hope is that, once it's resolved there, the most recent version of pefile will show up and be installable that way. If anybody knows better, please let me know.

**Comment by gmacon** [comment]
I noticed that PyPI's "simple" interface shows nothing for pefile: <https://pypi.python.org/simple/pefile/>. The simple interface is the one pip uses to figure out what to install, but I don't know anything particular about how PyPI populates that page.

**Comment by stevelacey** [comment]
@erocarrera looks like this is out of your hands now, but I think deleting the project has made pefile totally uninstallable from pip via PyPi – I guess the only thing to do now (since my build is broken) is switch to installing via `-e git+https://github.com/erocarrera/pefile.git@6c44132#egg=pefile`?

**Comment by stevelacey** [comment]
saying that, I can't get the above to work, giving up and ripping my pefile functionality for the time being :|

**Comment by fishtek** [comment]
Just wanted to mention I tried this today, and it appears to be working now!
```
root@9366a4700430:/# pip install pefile
Downloading/unpacking pefile
  Downloading pefile-2016.3.28.tar.gz (58kB): 58kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pefile/setup.py) egg_info for package pefile
    
    warning: no previously-included files found matching 'run_tests.py'
    warning: no previously-included files found matching 'requirements.txt'
    warning: no previously-included files found matching 'README.md'
    no previously-included directories found matching 'tests'
Downloading/unpacking future (from pefile)
  Downloading future-0.15.2.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_root/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Installing collected packages: pefile, future
  Running setup.py install for pefile
    
    warning: no previously-included files found matching 'run_tests.py'
    warning: no previously-included files found matching 'requirements.txt'
    warning: no previously-included files found matching 'README.md'
    no previously-included directories found matching 'tests'
  Running setup.py install for future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
    Installing pasteurize script to /usr/local/bin
    Installing futurize script to /usr/local/bin
Successfully installed pefile future
Cleaning up...
```

**Comment by matysek** [comment]
yes, I confirm this:

```
» pip install pefile
Collecting pefile
  Downloading pefile-2016.3.28.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Collecting future (from pefile)
  Using cached future-0.15.2.tar.gz
Building wheels for collected packages: pefile, future
  Running setup.py bdist_wheel for pefile ... done
  Stored in directory: /home/user/.cache/pip/wheels/1a/ae/da/15d1fb97a947267dd1b3330bc1ead40c7adb76cfbdc6b0eff6
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/user/.cache/pip/wheels/d9/04/36/6bd807b5148e7c929d8f0991cc943a81f3287030a1b352e3fc
Successfully built pefile future
Installing collected packages: future, pefile
Successfully installed future-0.15.2 pefile-2016.3.28
```

**Comment by techtonik** [comment]
@matysek you can close this then.

**Comment by matysek** [comment]
It is fixed .. tested tooooday and it installed the latest version:
```
$ pip install pefile
Installing collected packages: future, pefile
Successfully installed future-0.16.0 pefile-2017.8.1
```
